//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-10-20 18:18:26 Modify by Ocean
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Linq;

namespace SimpleEntityFramework.Models
{
    /// <summary>
    /// 实体数据库属性帮助类
    /// </summary>
	public static class ModelsPropertiesHelper
	{
	    /// <summary>
        /// 获取实体配置根节点
        /// </summary>
        /// <returns></returns>
		public static XDocument GetPropertiesRoot()
		{
			return XDocument.Load("ModelsProperties.xml");
		}
	}
}
