

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-10-14 16:03:57 Modify by Ocean
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace SimpleEntityFramework.Models
{    
	/// <summary>
    /// 实体Company
    /// </summary>  
    public partial class Company : SimpleEntityFramework.ModelBase.ModelBase 
    {
		#region 属性
        
        /// <summary>
        /// 
        /// </summary>        
        public string Name { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public DateTime CreateTime { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public int CreatorId { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public int? LastModifierId { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? LastModifyTime { get; set; }
		 
		#endregion

    }

	/// <summary>
    /// 实体User
    /// </summary>  
    public partial class User : SimpleEntityFramework.ModelBase.ModelBase 
    {
		#region 属性
        
        /// <summary>
        /// 
        /// </summary>        
        public string Name { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public string Account { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public string Password { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public string Email { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public string Mobile { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public int? CompanyId { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public string CompanyName { get; set; }
		
        /// <summary>
        /// 用户状态  0正常 1冻结 2删除
        /// </summary>        
        public int State { get; set; }
		
        /// <summary>
        /// 用户类型  1 普通用户 2管理员 4超级管理员
        /// </summary>        
        public int UserType { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? LastLoginTime { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public DateTime CreateTime { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public int CreatorId { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public int? LastModifierId { get; set; }
		
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? LastModifyTime { get; set; }
		 
		#endregion

    }

}

