using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-10-18 09:50:22 Modify by Ocean
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace SimpleEntityFramework.IBLL
{
	/// <summary>
    /// 业务层大接口
    /// </summary>
	public partial interface IBLLSession
	{
  
		#region 00 - ICompanyBLL接口访问对象

		/// <summary>
		/// ICompanyBLL接口访问对象
		/// </summary>		
		ICompanyBLL CompanyBLL{get;set;}
	
		#endregion
  
		#region 01 - IUserBLL接口访问对象

		/// <summary>
		/// IUserBLL接口访问对象
		/// </summary>		
		IUserBLL UserBLL{get;set;}
	
		#endregion
	}
}