//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-10-17 21:36:15 Modify by Ocean
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using SimpleEntityFramework.IBLL;
using SimpleEntityFramework.Models;

namespace SimpleEntityFramework.IBLL
{
  
	/// <summary>
    /// Company的扩展BLL
    /// </summary>
	public partial interface ICompanyBLL : IBaseBLL<Company>
	{
	}
  
	/// <summary>
    /// User的扩展BLL
    /// </summary>
	public partial interface IUserBLL : IBaseBLL<User>
	{
	}
}