using System;
using SimpleEntityFramework.Models;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-10-17 20:44:06 Modify by Ocean
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace SimpleEntityFramework.IDAL
{
  
	/// <summary>
    /// Company的扩展Dal
    /// </summary>
	public partial interface ICompanyDal : IBaseDal<Company>
	{
	}
  
	/// <summary>
    /// User的扩展Dal
    /// </summary>
	public partial interface IUserDal : IBaseDal<User>
	{
	}
}