//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-10-18 10:06:51 Modify by Ocean
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using SimpleEntityFramework.IBLL;
using SimpleEntityFramework.Models;

namespace SimpleEntityFramework.BLL
{
  
	/// <summary>
    /// Company的扩展BLL
    /// </summary>
	public partial class CompanyBLL : BaseBLL<Company>,ICompanyBLL
	{
		protected override void SetDal()
	    {
	        _dal = DBSession.CompanyDal;
	    }
	}
  
	/// <summary>
    /// User的扩展BLL
    /// </summary>
	public partial class UserBLL : BaseBLL<User>,IUserBLL
	{
		protected override void SetDal()
	    {
	        _dal = DBSession.UserDal;
	    }
	}
}